### ISSUE TITLE
Crashing after invalid results

### ISSUE THREAD

**Issue by virtuald** [wpilibsuite/sysid#411]
When I load an analysis that has bad results in it, when I reset and load a different file then I get a SIGFPE. On Windows I think it just crashes, but I can't be sure whether it was the same error. Here's the stacktrace:

```
Thread 1 "sysid" received signal SIGFPE, Arithmetic exception.
0x00005555555daf23 in sysid::OLS(std::vector<double, std::allocator<double> > const&, unsigned long) ()
Missing separate debuginfos, use: dnf debuginfo-install elfutils-libelf-0.186-1.fc34.x86_64 expat-2.4.4-1.fc34.x86_64 glibc-2.33-21.fc34.x86_64 libX11-1.7.2-3.fc34.x86_64 libX11-xcb-1.7.2-3.fc34.x86_64 libXau-1.0.9-6.fc34.x86_64 libXcursor-1.2.0-5.fc34.x86_64 libXext-1.3.4-6.fc34.x86_64 libXfixes-6.0.0-1.fc34.x86_64 libXi-1.7.10-6.fc34.x86_64 libXinerama-1.1.4-8.fc34.x86_64 libXrender-0.9.10-14.fc34.x86_64 libXxf86vm-1.1.4-16.fc34.x86_64 libdrm-2.4.109-1.fc34.x86_64 libedit-3.1-38.20210714cvs.fc34.x86_64 libgcc-11.2.1-9.fc34.x86_64 libglvnd-1.3.3-1.fc34.x86_64 libglvnd-glx-1.3.3-1.fc34.x86_64 libselinux-3.2-1.fc34.x86_64 libstdc++-11.2.1-9.fc34.x86_64 libxcb-1.13.1-7.fc34.x86_64 libxshmfence-1.3-8.fc34.x86_64 llvm-libs-12.0.1-1.fc34.x86_64 mesa-dri-drivers-21.1.8-3.fc34.x86_64 ncurses-libs-6.2-4.20200222.fc34.x86_64 pcre2-10.36-4.fc34.x86_64 sssd-client-2.5.2-2.fc34.x86_64
(gdb) bt
#0  0x00005555555daf23 in sysid::OLS(std::vector<double, std::allocator<double> > const&, unsigned long) ()
#1  0x00005555555f36b3 in sysid::CalculateFeedforwardGains(sysid::Storage const&, sysid::AnalysisType const&) ()
#2  0x00005555555af466 in sysid::AnalysisManager::CalculateFeedforward() ()
#3  0x000055555558d1c5 in sysid::Analyzer::UpdateFeedforwardGains() ()
#4  0x000055555558d2ad in sysid::Analyzer::PrepareData() ()
#5  0x000055555558dd01 in sysid::Analyzer::SelectFile() ()
#6  0x0000555555590500 in sysid::Analyzer::Display() ()
#7  0x000055555560d0c3 in glass::Window::Display (this=0x555556dd4be0) at /__w/allwpilib/allwpilib/glass/src/lib/native/cpp/Window.cpp:65
#8  0x0000555555602eac in glass::WindowManager::DisplayWindows (this=<optimized out>) at /__w/allwpilib/allwpilib/glass/src/lib/native/cpp/WindowManager.cpp:112
#9  0x0000555555624a3f in std::function<void ()>::operator()() const (this=<optimized out>) at /usr/include/c++/8/bits/std_function.h:260
#10 wpi::gui::CommonRenderFrame () at /__w/allwpilib/allwpilib/wpigui/src/main/native/cpp/wpigui.cpp:357
#11 0x0000555555626dc0 in wpi::gui::PlatformRenderFrame () at /__w/allwpilib/allwpilib/wpigui/src/main/native/opengl3/wpigui_opengl3.cpp:81
#12 0x000055555562480c in wpi::gui::Main () at /__w/allwpilib/allwpilib/wpigui/src/main/native/cpp/wpigui.cpp:296
#13 0x00005555555a9f85 in Application(std::basic_string_view<char, std::char_traits<char> >) ()
#14 0x000055555558bd58 in main ()
```

I think this is the file that was loaded first. It's 'bad' when you switch the analysis from 'combined' to 'right'. [sysid_data20220320-194234.zip](https://github.com/wpilibsuite/sysid/files/8313279/sysid_data20220320-194234.zip).

... I'm trying to reproduce the issue and I can't do it. I think I was just loading one analysis after another after another.

**Comment by calcmogul** [comment]
I can't reproduce it either.
